root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ./cmd/web"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata", "frontend/node_modules"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "env", "yml"]
kill_delay = 2
log = "build-errors.log"
send_interrupt = true
stop_on_error = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
time = false

[misc]
clean_on_exit = true 